//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiriMotoTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KiriMotoTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;settings&quot;: {
        ///		&quot;bounds&quot;: {
        ///			&quot;min&quot;: [
        ///				0,
        ///				0,
        ///				0
        ///			],
        ///			&quot;max&quot;: [
        ///				0,
        ///				0,
        ///				0
        ///			]
        ///		},
        ///		&quot;origin&quot;: {
        ///			&quot;x&quot;: -5,
        ///			&quot;y&quot;: 5,
        ///			&quot;z&quot;: 0.01
        ///		},
        ///		&quot;stock&quot;: {
        ///			&quot;x&quot;: 10,
        ///			&quot;y&quot;: 10,
        ///			&quot;z&quot;: 0,
        ///			&quot;center&quot;: {
        ///				&quot;x&quot;: 0,
        ///				&quot;y&quot;: 0,
        ///				&quot;z&quot;: 0
        ///			}
        ///		},
        ///		&quot;tools&quot;: [
        ///			{
        ///				&quot;id&quot;: 1780610382471,
        ///				&quot;number&quot;: 9,
        ///				&quot;type&quot;: &quot;ballmill&quot;,
        ///				&quot;name&quot;: &quot;ball 0.8mm&quot;,
        ///				&quot;metric&quot;: true,
        ///				&quot;shaft_diam&quot;: 0.8,
        ///				&quot;shaft_len&quot;: 25,
        ///				&quot;flute_diam&quot;: 1,
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankWorkspace {
            get {
                return ResourceManager.GetString("BlankWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;code&gt;[A-Z])(?&lt;value&gt;-{0,1}\d+(\.\d+){0,1})).
        /// </summary>
        internal static string rxGCodeLine {
            get {
                return ResourceManager.GetString("rxGCodeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;numeric&gt;-{0,1}\d+(\.\d+){0,1}).
        /// </summary>
        internal static string rxNumeric {
            get {
                return ResourceManager.GetString("rxNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:outer\s+loop\s+vertex\s+(?&lt;x&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})\s+(?&lt;y&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})\s+(?&lt;z&gt;-{0,1}[0-9]+(\.[0-9]+){0,1})\s+)).
        /// </summary>
        internal static string rxStlVector {
            get {
                return ResourceManager.GetString("rxStlVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform tasks on Kiri:Moto files.
        ///
        ///Syntax:
        ///KiriMotoTools /action:{ActionName}
        ///    [/configfile:{Filename}]
        ///    [/infile:{Filename}] [/outfile:{Filename}]
        ///    [/option:{OptionName[,OptionValue]}]
        ///    [/properties:{NameValueArray}]
        ///    [/tool:{SelectedToolName}]
        ///    [/workingpath:{FolderName}]
        ///    [/wait]
        ///    [/?]
        ///
        ///All parameters can be prefixed with either &apos;/&apos; or &apos;--&apos;.
        ///
        /// * -    Actions marked with an asterisk are only supported within a
        ///        configuration file.
        ///
        ///    /action     -   Descr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
